spring.application.name=quiz-platform
server.port=8080

# MySQL configuration
spring.datasource.url=jdbc:mysql://localhost:3306/quiz_platform
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# This project stores runtime data using manual DSA structures for academic evaluation.
# Set this to false when MySQL is not available during local testing.
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
